#!/bin/zsh
cd "$(dirname "$0")"
rm -rf build
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_OSX_ARCHITECTURES="x86_64;arm64" -D BUILD_SHARED_LIBS=ON -D CMAKE_C_COMPILER=clang ../
make
